### ISSUE TITLE
Example required for stop functionality

### ISSUE THREAD

**Issue by LilYea** [ChrisHanuta/node-red-contrib-velux#10]
Hi everyone,

I am experimenting with the KLF adapter.
There is a really good example from malansk and he did a very good job there, which already helped me.
Thanks for the provided information.
However I have some issues implementing the stop button for the dashboard.
Can someone help me with that?
I am using the dashboard button and filling it with payload JSON {"rawValue":"0xD200"}. I am connecting that to a Velux node. 
In the Velux node I set it to target. I am keeping topic "name" the same (in velux node and button node).
However it is not interpreted by Velux.
While debugging the node as well as the button it always turns out, that the the button puts out msg.payload : object rawValue : 0xD200.

Thank you

**Comment by LilYea** [comment]
<img width="663" alt="Bildschirmfoto 2021-03-26 um 09 53 17" src="https://user-images.githubusercontent.com/81388687/112607091-1a35eb80-8e19-11eb-89b5-78c40ab872aa.png">

<img width="490" alt="Bildschirmfoto 2021-03-26 um 09 56 32" src="https://user-images.githubusercontent.com/81388687/112607476-8dd7f880-8e19-11eb-9cb3-30f5064444a6.png">
![Uploading Bildschirmfoto 2021-03-26 um 09.57.16.png…]()

**Comment by malansk** [comment]
Hello,

I have different settings, try to set the Checkbox „emulate a button click when message arrives“.
But this function you probably don’t need so this should not make a difference.
Probably the „Topic“ has to be defined not as „msg“.

But I can´t remember how to change that.



***@***.***D7222B.EF4AE500]

***@***.***D7222B.EF4AE500]

Mit freundlichem Gruß
Martin Lansky

Von: ***@***.***>
Gesendet: Freitag, 26. März 2021 09:57
An: ***@***.***>
Cc: ***@***.***>
Betreff: Re: [PLCHome/node-red-contrib-velux] Example required for stop functionality (#10)


[Bildschirmfoto 2021-03-26 um 09 53 17]<https://user-images.githubusercontent.com/81388687/112607091-1a35eb80-8e19-11eb-89b5-78c40ab872aa.png>

[Bildschirmfoto 2021-03-26 um 09 56 32]<https://user-images.githubusercontent.com/81388687/112607476-8dd7f880-8e19-11eb-9cb3-30f5064444a6.png>
![Uploading Bildschirmfoto 2021-03-26 um 09.57.16.png…]()

**Comment by LilYea** [comment]
Hi malansk,

thanks for the help.
I changed to string in the drop down and now it works.
Perfect

<img width="454" alt="Bildschirmfoto 2021-03-26 um 11 16 21" src="https://user-images.githubusercontent.com/81388687/112617005-b3b6ca80-8e24-11eb-95cf-2c22c84ae491.png">
