### ISSUE TITLE
Velux Api Node

### ISSUE THREAD

**Issue by bergstermann** [ChrisHanuta/node-red-contrib-velux#11]
Hello,
I have selected the datasource in the velux api node , but I can ´t choose a api. Do you have any idea? The velux node works without problems.

**Comment by bergstermann** [comment]
When I want to select the api in the drop down menu, I see only a black line.

![Screenshot](https://user-images.githubusercontent.com/86686293/124323179-2997a400-db81-11eb-8ad6-4597c2c5bcfa.jpg)

**Comment by bergstermann** [comment]
To solve the problem in an easy way, I have replace the drop down menu by a input field. So it works with redmatic on homamtic CCU3.

file: velux-api.html
line 13: `<input type="text" id="node-input-api" style="width:70%;">` 
and line 18: `<input type="text" id="node-input-ntf" style="width:70%;" >`

**Comment by PLCHome** [comment]
The http://>nodered page</velux/req and http://>nodered page</velux/ntf listener only works if the velux-connetion-node is connected on startup.

Make shure that the connection ist correct. Then restart nodered. 
After this press >ctrl<+F5 on browser to refresh the Page.
