### ISSUE TITLE
Example for Stop command

### ISSUE THREAD

**Issue by fgathercoupa** [ChrisHanuta/node-red-contrib-velux#13]
Hi,

thanks for the library. Do you happen to know how to implement a stop function and could provide an example? Unfortunately, the API node seems to be broken right now, and it is hard to experiment with it. 

Best Regards

**Comment by PLCHome** [comment]
Stop what?
https://github.com/PLCHome/velux-klf200-api/blob/master/technical%20specification%20for%20klf%20200%20api.pdf

10.2?

11.11?

13.4?

**Comment by Michael-Hennemann** [comment]
Hi! :) 
I guess the STOP from 10.2 would do the trick. 
The remote that came with my Velux window (3LI D11 WW) has 3 buttons on it: UP, DOWN, STOP, but I don't want to use it as I already got another smart home solution, they don't fit to my other buttons and in general they are kind of ugly ;-)

I already figured that setting target to 100 makes it go up, and setting it to 0 makes it go down. So a command for making it stop if I want it somewhere in between would be nice. 

If I understand the Velux document correctly, you can read the current position and write it instantaneously back as target? 

cheers
Michael

**Comment by Michael-Hennemann** [comment]
Hm, ok, I guess it's not that simple. 
To make the actuator stop, one would have to send the GW_COMMAND_SEND_REQ CURRENT (0xD200) via the API-Node I think. Like in 10.2 of the API documentation. 

No idea how to do that. :-|

Any help/example appreciated !  :-)

**Comment by ckohrt** [comment]
Hi, 
this issue is maybe old - but still open. So I required exactly this and came to the following solution: See appended file for import to node red.
I have added the Velux node, three buttons including stop with change nodes and shutter graphics. The configuration for the stop button change node is:

msg.payload={"rawValue":"0xD200"}
msg.topic=velux:write: id:0:valuetype:CURRENT:

(without space before "id")

Hope that helps!

Cheers
Christian

[flows (7).zip](https://github.com/PLCHome/node-red-contrib-velux/files/8128095/flows.7.zip)

**Comment by Michael-Hennemann** [comment]
> Hi, this issue is maybe old - but still open. So I required exactly this and came to the following solution: See appended file for import to node red. I have added the Velux node, three buttons including stop with change nodes and shutter graphics. The configuration for the stop button change node is:
> 
> msg.payload={"rawValue":"0xD200"} msg.topic=velux:write: id:0:valuetype:CURRENT:
> 
> (without space before "id")
> 
> Hope that helps!
> 
> Cheers Christian
> 
> [flows (7).zip](https://github.com/PLCHome/node-red-contrib-velux/files/8128095/flows.7.zip)

Works perfectly! 
Thanks a lot!
