### ISSUE TITLE
Error "that the node reported waiting for power"

### ISSUE THREAD

**Issue by r4v3n-MD** [ChrisHanuta/node-red-contrib-velux#14]
Hi community,
first of all, thank you for your work and the nodes! 
I need a little help. When I shut down my Velux blinds the nodes get the error "that the node reported waiting for power". The error ends after the blind is in end position. During this time each command is ignored. 
Following my configuration node: 

![grafik](https://user-images.githubusercontent.com/87266981/125194976-d645e580-e253-11eb-807b-176df2f6a15c.png)

 Do you have any idea how I can fix the problem?

**Comment by Michael-Hennemann** [comment]
Hi! I also see this "error" message during operation of my integra window and blinds but I am able to issue new commands. 
When the blinds are rolling down, I can press the "up" button and the blinds stop and go up again.
