### ISSUE TITLE
KLF200 crashes every couple of minutes

### ISSUE THREAD

**Issue by bhuebschen** [ChrisHanuta/node-red-contrib-velux#17]
I've running a KLF200 with 6 Velux dormer windows .. when the nodes are not connected to the device, it doesn't crash.. but after reattaching the node to the KLF200...

I'm getting the message, that the connection has been refused... restarting works.. but just a few minutes

**Comment by PLCHome** [comment]
Can you open the WEB-UI interface of the KLF via the LAN interface or do you have to set up a separate WLAN connection.?

Additionally I need a little more information.
The log is definitely required.
