### ISSUE TITLE
Get state info during shutter movement

### ISSUE THREAD

**Issue by ckohrt** [ChrisHanuta/node-red-contrib-velux#19]
Hi,
is it possible to get the state info during movement of the shutter?
With the "Velux Nodes" node with input
velux:load:id:0:valuetype:CURRENT:
and I can get back GW_GET_NODE_INFORMATION_NTF which I am after. But this does not work during movement. I get some messages but the state is not actualized. (So it starts at 0% and when finished it jumps to 100%. The status messages in between have all 0%.)
Any possibility to get this info?

Thanks,
Christian

**Comment by PLCHome** [comment]
It does what it does. I have no influence on that. When the monitor is activated, the KLF sends the data as often as it wants. I assume that the devices save the energy and the clerk only passes on the received information.

**Comment by ckohrt** [comment]
Ok, thanks
