### ISSUE TITLE
Simple way to get all node list

### ISSUE THREAD

**Issue by s0nik42** [ChrisHanuta/node-red-contrib-velux#22]
Hello,

Maybe I'm not using the API properly, but is that a simple way to get the list of Nodes  (the node IDs are enough) attached to a klf-200  ? I would like this to be manually triggered. 

I tried 2 different approach : 
1 . Use an [inject] node  + a [Velux Nodes] but the [Velux nodes] also fire events periodically. 
2. I tried to send a msg.payload = { "apiText":"GW_GET_ALL_NODES_INFORMATION_REQ" } to a [Velux API] but it just output _CFM  and all information arrived through notifications :/ 

What I'm trying to achieve is a one time flow creating a group per node ;) .

**Comment by PLCHome** [comment]
Did you select the correct answers in the node?
Is the monitor activated?
