### ISSUE TITLE
Velux Error: Can't get scene list

### ISSUE THREAD

**Issue by giannicattoni** [ChrisHanuta/node-red-contrib-velux#4]
I configured the node and there are no connection errors.
My windows are not displayed in the drop-down menu.
It would be nice to have an example.

Many thanks
Gianni

**Comment by PLCHome** [comment]
Do you see the nodes (devices) in the velux-nodes node?
Did you save scene in the KLF-200 and did you see them in the KLF-200?
Scenes can also be stored in a KLR 200. These must first be imported into the KLF200.

I have problems with Firefox. 
![grafik](https://user-images.githubusercontent.com/29116097/57584010-ed9fb180-74d6-11e9-9ae6-41cf567616c1.png)
Please use chrome.
![grafik](https://user-images.githubusercontent.com/29116097/57583825-d8298800-74d4-11e9-8845-312700eb546b.png)

you can test the list via the browser {your node red adress}/velux/scenes or {your node red adress}/velux/ nodes for the nodes

![grafik](https://user-images.githubusercontent.com/29116097/57583903-b7adfd80-74d5-11e9-9815-22fb3f7ec83c.png)

![grafik](https://user-images.githubusercontent.com/29116097/57583870-5d14a180-74d5-11e9-82b1-a398457abff1.png)

**Comment by giannicattoni** [comment]
Thank's for your answer.

> Do you see the nodes (devices) in the velux-nodes node?
> 
No, before I had 12 nodes, now I deleted 6 to try.

> Did you save scene in the KLF-200 ans did you see them in the KLF-200?
Scenes can also be stored in a KLR 200. These must first be imported into the KLF200.
> 
No, I don't use scenes.

I use Chrome.

This http://192.168.1.101:1880/velux/nodes return:
[]

Thank's
Gianni

**Comment by PLCHome** [comment]
You say
> No, I don't use scenes.
> Can't get scene list

I'm confused ??

> This http://192.168.1.101:1880/velux/nodes return:
[]

Is the KLF-200 connected?
Does the KLF-200 have the firmware 0.2.0.0.71?
Please check this

```
[{"id":"857c19c0.fdb9c","type":"Velux Api","z":"7a7b8638.9b31d8","name":"","datasource":"","api":"8","ntf":null,"topic":"","x":960,"y":420,"wires":[["d7ddfc5a.91d988"]]},{"id":"d7ddfc5a.91d988","type":"debug","z":"7a7b8638.9b31d8","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","x":1130,"y":420,"wires":[]},{"id":"eb8d7893.98eb68","type":"inject","z":"7a7b8638.9b31d8","name":"","topic":"","payload":"","payloadType":"date","repeat":"10","crontab":"","once":true,"onceDelay":0.1,"x":770,"y":420,"wires":[["857c19c0.fdb9c"]]}]
```

Somtime an factory reste will help.

**Comment by giannicattoni** [comment]
I do a factory reset.
If there a no scenes the error "Can't get scene list" appears.
So I created a scene that I don't use.
I can access the nodes only by ID, not the name, but it is not a problem.
Now I can command and see the state.

**Comment by PLCHome** [comment]
> I can access the nodes only by ID, not the name, but it is not a problem.

so readme.md:

> node index: This is the index of the device (node) within the KLF200. In the dropdown, the index and the name are displayed when the combo box is empty.
