### ISSUE TITLE
Update Node-Red V7.0 to include node-red-contrib-velux V0.0.4 

### ISSUE THREAD

**Issue by malansk** [ChrisHanuta/node-red-contrib-velux#7]
I am running latest Node-Red V7.0 on Homematic CCU3.
In the Palette manager, node-red-contrib-velux is offered in the version 0.0.3.

Are there any plans to to include latest version 0.0.4 in Node-Red ?

**Comment by PLCHome** [comment]
node-red-contrib-velux version 0.0.4 was not published to NPM.
